### ISSUE TITLE
Problem of letter case

### ISSUE THREAD

**Issue by ALBERT5400** [JoelFH23/uqload-downloader-python#3]
So, I saw your projet when I searched a way to download a lot's of video.
For this I made an excel file with the different argument in different column, but when you pas a Line it put tabulation between what was an other column. When we run the command line it say Error of link because it's there a tabulation/space between quote and https. Also It broke the command line if it's there a Tabulation in the name you put of the file you download.
So I have to idea allow more letter case or put in documentation.

Thanks a lot for your work

**Comment by JoelFH23** [comment]
Thank you for using the script.
I am currently working on a new version for parallel downloads.

But I can help you

1. download the file [load_file.py.txt](https://github.com/JoelFH23/uqload-downloader-python/files/12447405/load_file.py.txt) and [example_file.xlsx](https://github.com/JoelFH23/uqload-downloader-python/files/12447402/example_file.xlsx).
2. Add them to the root of the project.
3. run the script: python load_file.py
4. now you can load your own Excel file, modifying line 18 of the load_file.py file.

Note: remember to install pandas and openpyxl.

**Comment by ALBERT5400** [comment]
Thanks
